---
name: DBIx-Class-UUIDColumns
version: 0.01000
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
abstract: Implicit uuid columns
license: perl
requires:
  DBIx::Class: 0.06002
recommends:
  APR::UUID: 0
  Data::UUID: 0
  UUID: 0
  Win32::Guidgen: 0
  Win32API::GUID: 0
build_requires:
  DBD::SQLite: 1.11
  SQL::Translator: 0.07
provides:
  DBIx::Class::UUIDColumns:
    file: lib/DBIx/Class/UUIDColumns.pm
    version: 0.01000
  DBIx::Class::UUIDColumns::UUIDMaker:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker.pm
  DBIx::Class::UUIDColumns::UUIDMaker::APR::UUID:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker/APR/UUID.pm
  DBIx::Class::UUIDColumns::UUIDMaker::Data::UUID:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker/Data/UUID.pm
  DBIx::Class::UUIDColumns::UUIDMaker::Data::Uniqid:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker/Data/Uniqid.pm
  DBIx::Class::UUIDColumns::UUIDMaker::UUID:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker/UUID.pm
  DBIx::Class::UUIDColumns::UUIDMaker::Win32::Guidgen:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker/Win32/Guidgen.pm
  DBIx::Class::UUIDColumns::UUIDMaker::Win32API::GUID:
    file: lib/DBIx/Class/UUIDColumns/UUIDMaker/Win32API/GUID.pm
generated_by: Module::Build version 0.26
