--- 
abstract: Implicit uuid columns
author: Chia-liang Kao <clkao@clkao.org>
build_requires: 
  DBD::SQLite: 1.11
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-UUIDColumns
no_index: 
  directory: 
    - inc
    - t
recommends: 
  APR::UUID: 0
  Data::UUID: 0
  Data::Uniqid: 0
  UUID: 0
  Win32::Guidgen: 0
  Win32API::GUID: 0
requires: 
  DBIx::Class: 0.07005
  perl: 5.8.1
tests: t/*.t t/*/*.t
version: 0.01001
